# config.yaml
devices:
  - name: "Router1"
    device_type: "cisco_ios"
    host: "192.168.1.1"
    username: "admin"
    password: "cisco"
    secret: "enable_password"

#  - name: "Switch1"
#    device_type: "cisco_ios"
#    host: "192.168.1.2"
#    username: "admin"
#    password: "admin123"
#    secret: "enable_password"

ftp:
  host: "ftp.example.com"
  username: "ftp-user"
  password: "ftp-passwords"
  directory: "/backups"
